In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
data = {"Country":["France","Spain","Germany","Spain","Germany","France","Spain","France","Germany","France"],
        "Age":[44,27,30,38,40,35,np.nan,48,50,37],
        "Salary":[72000,48000,54000,61000,np.nan,58000,52000,79000,83000,67000],    # preparing the data
        "Purchased":["No","Yes","No","No","Yes","Yes","No","Yes","No","Yes"]
       }

data = pd.DataFrame(data)   # Converting to dataframe
data

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [7]:
X_raw = data.iloc[:,:-1]  # Extracting the fatures columns
X_raw

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [11]:
Y_raw = data.iloc[:,-1]  # Extracting the target column
Y_raw

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [14]:
DfX_raw = X_raw.values  # Extacting the features of the dataframe in numpy array form
DfY_raw = Y_raw.values
X = X_raw.copy()        # Extacting the features of the dataframe in dataframe form
Y = Y_raw.copy()
print(X)
print(DfX_raw)

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0
[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]

In [16]:
X.info() # Displaying the information of the dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  10 non-null     object
 1   Age      9 non-null      float64
 2   Salary   9 non-null      float64
dtypes: float64(2), object(1)
memory usage: 368.0+ bytes

In [17]:
X_pd = pd.DataFrame(DfX_raw) # Changing the numpy array into dataframe
X_pd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       10 non-null     object
 1   1       9 non-null      object
 2   2       9 non-null      object
dtypes: object(3)
memory usage: 368.0+ bytes

In [18]:
X_pd = X_pd.values # Changing the dataframe into numpy array
X_pd

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [19]:
X.isnull().sum()  # Finding the nuber of missing values

Country    0
Age        1
Salary     1
dtype: int64

In [20]:
Y.isnull().sum()

0

In [21]:
X.fillna(0)  # Filling the NaN values with 0

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      0.0
5   France  35.0  58000.0
6    Spain   0.0  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [22]:
X.replace(0,np.nan) # Replacing the 0 values with Nan values

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [25]:
idx_no = X.columns.get_loc('Age')  # Getting the index number of a feature
idx_no

1

In [26]:
X.iloc[:,1] = X.iloc[:,1].fillna(5) # Filling NaN values in a specific column 
X

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   5.0  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [29]:
X = data.iloc[:,:-1]
X

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [32]:
# Simple imputer is a class which is used to handle the missing values with simple strategies
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan,strategy="mean")  # Filling the missing values with mean
X.iloc[:,1:3] = imputer.fit_transform(X.iloc[:,1:3])
X

   Country        Age        Salary
0   France  44.000000  72000.000000
1    Spain  27.000000  48000.000000
2  Germany  30.000000  54000.000000
3    Spain  38.000000  61000.000000
4  Germany  40.000000  63777.777778
5   France  35.000000  58000.000000
6    Spain  38.777778  52000.000000
7   France  48.000000  79000.000000
8  Germany  50.000000  83000.000000
9   France  37.000000  67000.000000

In [39]:
X = data.iloc[:,:-1]
imputer = SimpleImputer(missing_values=np.nan,strategy="constant",fill_value=50)
X.iloc[:,1:3] = imputer.fit_transform(X.iloc[:,1:3])
X

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0     50.0
5   France  35.0  58000.0
6    Spain  50.0  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [40]:
X = data.iloc[:,:-1]
imputer = SimpleImputer(missing_values=np.nan,strategy="median")
X.iloc[:,1:3] = imputer.fit_transform(X.iloc[:,1:3])
X

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0  61000.0
5   France  35.0  58000.0
6    Spain  38.0  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [41]:
X = data.iloc[:,:-1]
imputer = SimpleImputer(missing_values=np.nan,strategy="most_frequent")
X.iloc[:,1:3] = imputer.fit_transform(X.iloc[:,1:3])
X

C:\Users\SILICON\anaconda3\lib\site-packages\sklearn\impute\_base.py:49: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode = stats.mode(array)

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0  48000.0
5   France  35.0  58000.0
6    Spain  27.0  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [43]:
imputer = SimpleImputer(missing_values=np.nan,strategy="median")
X_pd[:,1:3] = imputer.fit_transform(X_pd[:,1:3])
X_pd

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 61000.0],
       ['France', 35.0, 58000.0],
       ['Spain', 38.0, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

# Encoding Categorical Data

In [45]:
X = pd.get_dummies(X,columns=["Country"]) # One-Hot Encoding
X

    Age   Salary  Country_France  Country_Germany  Country_Spain
0  44.0  72000.0               1                0              0
1  27.0  48000.0               0                0              1
2  30.0  54000.0               0                1              0
3  38.0  61000.0               0                0              1
4  40.0  48000.0               0                1              0
5  35.0  58000.0               1                0              0
6  27.0  52000.0               0                0              1
7  48.0  79000.0               1                0              0
8  50.0  83000.0               0                1              0
9  37.0  67000.0               1                0              0

In [46]:
X_pd = X_pd.get_dummies(X_pd,columns=["Country"])
X_pd

AttributeError: 'numpy.ndarray' object has no attribute 'get_dummies'

In [47]:
X = data.iloc[:,:-1]